remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: ['Predicting Snowpack in California’s Sierra Nevada Mountains']
description: [What the dog doin']
logo: https://raw.githubusercontent.com/Seiris21/ucb2022.snowcast/main/docs/assets/labeled.png
